name: PR Test

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: npm ci
      - name: Build TypeScript
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Run linter
        run: npm run lint
      # - name: Run Prettier
      #   run: npm run format:check
      - name: Check for outdated dependencies
        run: npm outdated --json | jq 'length == 0' || (echo "There are outdated dependencies!" && exit 1)
      - name: Check for security vulnerabilities
        run: npm audit --audit-level=moderate || (echo "There are security vulnerabilities!" && exit 1)
      - name: Check for unused dependencies
        run: npx depcheck || (echo "There are unused dependencies!" && exit 1)
      - name: Check for duplicate dependencies
        run: npx depcheck --duplicates || (echo "There are duplicate dependencies!" && exit 1)
